name: desafio_unizumi
description: Aplicación de trivia móvil en Flutter para proyecto universitario.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#0F2A44"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
          weight: 800
